theme: jekyll-theme-slate
title: Francisco (Paco) Holguin
description: Theoretical astrophysicist

header: /images/image.jpg

header_pages:
  - index.md
  - about.md
  - research.md
  - hobbies.md
  - cv.md
